name: Deploy Next.js to Cloud Run using GitHub Container Registry (GHCR) & Google Artifact Registry (GAR)

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: dreamfarer
        password: ${{ secrets.GHCR_PAT }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Login to Google Artifact Registry (GAR)
      run: |
        gcloud auth configure-docker europe-west6-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        GHCR_IMAGE="ghcr.io/sopra-fs25-group-20/sopra-fs25-group-20-client:latest"
        GAR_IMAGE="europe-west6-docker.pkg.dev/sopra-fs25-group-20-client/docker-repo/sopra-fs25-group-20-client:latest"
        docker build -f Dockerfile . \
          --tag $GHCR_IMAGE \
          --tag $GAR_IMAGE
        docker push $GHCR_IMAGE
        docker push $GAR_IMAGE

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy nextjs-app \
          --image=europe-west6-docker.pkg.dev/sopra-fs25-group-20-client/docker-repo/sopra-fs25-group-20-client:latest \
          --platform=managed \
          --region=europe-west6 \
          --allow-unauthenticated \
          --port=3000